arxiv:
  collab: "http://wwwlovre.appspot.com/resources/research/networks/acc/arXiv-acl"
  cite: "http://wwwlovre.appspot.com/resources/research/networks/acc/arXiv-act"

nsf:
  url_base: "http://api.nsf.gov/services/v1/awards.json"
  start_year: 1999
  end_year: 2019
