arxiv:
  collab: "http://wwwlovre.appspot.com/resources/research/networks/acc/arXiv-acl"
  cite: "http://wwwlovre.appspot.com/resources/research/networks/acc/arXiv-act"

nsf:
  url_base: "http://api.nsf.gov/services/v1/awards.json"
  start_year: 1993
  end_year: 2003

days:
  01: 31
  02: 28
  03: 31
  04: 30
  05: 31
  06: 30
  07: 31
  08: 31
  09: 30
  10: 31
  11: 30
  12: 31
